#!/usr/bin/env bash
set -euo pipefail

export $(xargs < "../../workr-release.env")

function main {
    clone-repository
    run-release
    show-latest-deb-download-link
}

function show-latest-deb-download-link {
    download_link=$(curl -sq "https://api.github.com/repos/sirikon/workr/releases/latest" | jq -r '.assets[0].browser_download_url')
    printf "%s\n" "Download link:" "${download_link}"
}

function clone-repository {
    log "Cloning repository..."
    if [ -d "./workr-git" ]; then
        (cd ./workr-git && git pull)
    else
        git clone https://github.com/sirikon/workr.git ./workr-git
    fi
    new-line
}

function run-release {
    log "Running release..."
    (cd ./workr-git && ./scripts/release)
    new-line
}

function log {
    printf "## %s\n" "$1"
}

function new-line {
    printf "\n"
}

main "$@"
