#!/usr/bin/env bash
set -euo pipefail

export "$(xargs < "../../workr-release.env")"
source "../../scripts.sh"

rm -rf ./out
clone-git-repository "https://github.com/sirikon/workr.git" "./workr-git"
(
    cd "./docker"
    docker-compose up --build builder
    docker cp "$(docker-compose ps -q builder)":/builder/out "../out"
)
log-newline

version="$(cat ./out/version)"
package-tar "./out/bin" "./out/workr-${version}-linux-amd64.tar.gz"
package-deb "./out/bin" "./out/workr-${version}-linux-amd64.deb" \
    "workr" \
    "${version}" \
    "https://github.com/sirikon/workr"

create-release "sirikon" "workr" "${version}" \
    "Workr" \
    "$(cd ./workr-git && git rev-parse HEAD)" \
    "$(cd ./workr-git && git log --format=%B -n 1 HEAD)"

upload-release-file "sirikon" "workr" "${version}" "./out/workr-${version}-linux-amd64.tar.gz"
upload-release-file "sirikon" "workr" "${version}" "./out/workr-${version}-linux-amd64.deb"

log-newline
show-latest-github-artifacts "sirikon" "workr"
